

export interface Video {
  id: number;
  src: string;
  user: string;
  avatar: string; // id from placeholder-images.json
  description: string;
  likes: string;
  comments: string;
  sends: string;
  isVerified?: boolean;
}

// To use your own videos, place your .mp4 files in the `videos` directory
// and update the `src` property for each video below with the correct filename.
export const videos: Video[] = [
  {
    id: 1,
    src: '/videos/video1.mp4',
    user: 'TryVistaCo',
    avatar: 'avatar1',
    description: 'This changed way more than I expected. #worthit',
    likes: '1.2k',
    comments: '345',
    sends: '102',
    isVerified: true,
  },
  {
    id: 2,
    src: '/videos/video2.mp4',
    user: 'Nexora',
    avatar: 'avatar2',
    description: 'I didn’t think I needed this.',
    likes: '2.5k',
    comments: '412',
    sends: '230',
    isVerified: true,
  },
  {
    id: 3,
    src: '/videos/video3.mp4',
    user: 'Brighta',
    avatar: 'avatar3',
    description: 'Why did no one tell me sooner? #foundit',
    likes: '5.1k',
    comments: '87',
    sends: '45',
    isVerified: true,
  },
  {
    id: 4,
    src: '/videos/video4.mp4',
    user: 'ShiftWorksOfficial',
    avatar: 'avatar4',
    description: 'The difference is actually wild.',
    likes: '3.3k',
    comments: '198',
    sends: '150',
    isVerified: true,
  },
  {
    id: 5,
    src: '/videos/video5.mp4',
    user: 'Micra',
    avatar: 'avatar5',
    description: 'Small switch, huge upgrade. #upgrade',
    likes: '10.2k',
    comments: '1.1k',
    sends: '980'
  },
  {
    id: 6,
    src: '/videos/video6.mp4',
    user: 'TrueTryGoods',
    avatar: 'avatar6',
    description: 'You’ll understand when you try it.',
    likes: '876',
    comments: '55',
    sends: '32',
    isVerified: true,
  },
  {
    id: 7,
    src: '/videos/video7.mp4',
    user: 'Prismo',
    avatar: 'avatar7',
    description: 'I can’t go back after this. #gamechanger',
    likes: '12.4k',
    comments: '2.3k',
    sends: '1.5k',
    isVerified: true,
  },
  {
    id: 8,
    src: '/videos/video8.mp4',
    user: 'EverydayEaseHQ',
    avatar: 'avatar8',
    description: 'I didn’t realize how much I’d use it.',
    likes: '4.9k',
    comments: '302',
    sends: '210',
    isVerified: true,
  },
  {
    id: 9,
    src: '/videos/video9.mp4',
    user: 'Knowli',
    avatar: 'avatar9',
    description: 'If you know, you know. #IYKYK',
    likes: '22k',
    comments: '4.5k',
    sends: '3.1k',
    isVerified: true,
  },
  {
    id: 10,
    src: '/videos/video10.mp4',
    user: 'CoreValueCollective',
    avatar: 'avatar10',
    description: 'Worth it for this alone.',
    likes: '7.8k',
    comments: '550',
    sends: '420'
  },
  {
    id: 11,
    src: '/videos/video11.mp4',
    user: 'Purio',
    avatar: 'avatar11',
    description: 'Seriously… why is this so good?',
    likes: '9.1k',
    comments: '600',
    sends: '512',
    isVerified: true,
  },
  {
    id: 12,
    src: '/videos/video12.mp4',
    user: 'PeakMethodCo',
    avatar: 'avatar12',
    description: 'It works better than I thought. #unexpected',
    likes: '6.5k',
    comments: '412',
    sends: '340',
    isVerified: true,
  },
  {
    id: 13,
    src: '/videos/video13.mp4',
    user: 'Hypeo',
    avatar: 'avatar13',
    description: 'The hype is real.',
    likes: '33k',
    comments: '7.8k',
    sends: '5.5k',
    isVerified: true,
  },
  {
    id: 14,
    src: '/videos/video14.mp4',
    user: 'SignalGoods',
    avatar: 'avatar14',
    description: 'This is your sign. #recommend',
    likes: '1.9k',
    comments: '201',
    sends: '180',
    isVerified: true,
  },
  {
    id: 15,
    src: '/videos/video15.mp4',
    user: 'ResultWaveCo',
    avatar: 'avatar15',
    description: 'Honestly shocked at the results.',
    likes: '4.0k',
    comments: '300',
    sends: '250'
  },
  {
    id: 16,
    src: '/videos/video16.mp4',
    user: 'Proofly',
    avatar: 'avatar16',
    description: 'I didn’t expect it to work.',
    likes: '5.2k',
    comments: '350',
    sends: '290',
    isVerified: true,
  },
  {
    id: 17,
    src: '/videos/video17.mp4',
    user: 'CoreObsessiveCo',
    avatar: 'avatar17',
    description: 'Kind of obsessed now. #newfavorite',
    likes: '15.3k',
    comments: '2.1k',
    sends: '1.8k',
    isVerified: true,
  },
  {
    id: 18,
    src: '/videos/video18.mp4',
    user: 'Solvia',
    avatar: 'avatar18',
    description: 'This solved a problem I didn’t know I had.',
    likes: '8.8k',
    comments: '702',
    sends: '650',
    isVerified: true,
  },
  {
    id: 19,
    src: '/videos/video19.mp4',
    user: 'SuperfanWorks',
    avatar: 'avatar19',
    description: 'Not me becoming a superfan.',
    likes: '3.1k',
    comments: '180',
    sends: '120',
    isVerified: true,
  },
  {
    id: 20,
    src: '/videos/video20.mp4',
    user: 'Deltik',
    avatar: 'avatar20',
    description: 'Wait until you see the difference. #beforeafter',
    likes: '9.9k',
    comments: '950',
    sends: '800'
  },
  {
    id: 21,
    src: '/videos/video21.mp4',
    user: 'TrustlineGoods',
    avatar: 'avatar21',
    description: 'Trust me, you’ll want this.',
    likes: '11.5k',
    comments: '1.5k',
    sends: '1.1k',
    isVerified: true,
  },
  {
    id: 22,
    src: '/videos/video22.mp4',
    user: 'EaseShiftBrand',
    avatar: 'avatar22',
    description: 'This made my life noticeably easier. #yesplease',
    likes: '7.2k',
    comments: '620',
    sends: '500',
    isVerified: true,
  },
  {
    id: 23,
    src: '/videos/video23.mp4',
    user: 'Ontry',
    avatar: 'avatar23',
    description: 'Try it once. That’s all.',
    likes: '2.4k',
    comments: '150',
    sends: '90',
    isVerified: true,
  },
  {
    id: 24,
    src: '/videos/video24.mp4',
    user: 'LittleLiftCo',
    avatar: 'avatar24',
    description: 'It’s the little things.',
    likes: '1.1k',
    comments: '90',
    sends: '40',
    isVerified: true,
  },
  {
    id: 25,
    src: '/videos/video25.mp4',
    user: 'UpgradeForge',
    avatar: 'avatar25',
    description: 'Game changer is an understatement. #upgrade',
    likes: '25k',
    comments: '3.2k',
    sends: '2.8k'
  },
  {
    id: 26,
    src: '/videos/video26.mp4',
    user: 'Waino',
    avatar: 'avatar26',
    description: 'I’m mad I waited this long.',
    likes: '6.7k',
    comments: '510',
    sends: '450',
    isVerified: true,
  },
  {
    id: 27,
    src: '/videos/video27.mp4',
    user: 'RightByInternet',
    avatar: 'avatar27',
    description: 'The internet was right about this.',
    likes: '18k',
    comments: '2.0k',
    sends: '1.6k',
    isVerified: true,
  },
  {
    id: 28,
    src: '/videos/video28.mp4',
    user: 'Legiti',
    avatar: 'avatar28',
    description: 'Okay… this is actually legit.',
    likes: '4.3k',
    comments: '380',
    sends: '300',
    isVerified: true,
  },
  {
    id: 29,
    src: '/videos/video29.mp4',
    user: 'DetailFactorCo',
    avatar: 'avatar29',
    description: 'I didn’t think it mattered—until now. #details',
    likes: '5.0k',
    comments: '400',
    sends: '350',
    isVerified: true,
  },
  {
    id: 30,
    src: '/videos/video30.mp4',
    user: 'Momentra',
    avatar: 'avatar30',
    description: 'Watch what happens next.',
    likes: '10.8k',
    comments: '1.2k',
    sends: '1.0k'
  },
  {
    id: 31,
    src: '/videos/video31.mp4',
    user: 'SmoothFlowCo',
    avatar: 'avatar31',
    description: 'This made everything smoother.',
    likes: '8.1k',
    comments: '680',
    sends: '550',
    isVerified: true,
  },
  {
    id: 32,
    src: '/videos/video32.mp4',
    user: 'Futuraa',
    avatar: 'avatar32',
    description: 'You’ll thank yourself later. #trustme',
    likes: '14.2k',
    comments: '1.9k',
    sends: '1.4k',
    isVerified: true,
  },
  {
    id: 33,
    src: '/videos/video33.mp4',
    user: 'NewFavGoods',
    avatar: 'avatar33',
    description: 'My new favorite thing.',
    likes: '3.9k',
    comments: '250',
    sends: '200',
    isVerified: true,
  },
  {
    id: 34,
    src: '/videos/video34.mp4',
    user: 'Edgia',
    avatar: 'avatar34',
    description: 'Instant upgrade. #yes',
    likes: '9.5k',
    comments: '800',
    sends: '710',
    isVerified: true,
  },
  {
    id: 35,
    src: '/videos/video35.mp4',
    user: 'GotMePointCo',
    avatar: 'avatar35',
    description: 'This is the part that got me.',
    likes: '6.1k',
    comments: '450',
    sends: '380'
  },
  {
    id: 36,
    src: '/videos/video36.mp4',
    user: 'GenioGoods',
    avatar: 'avatar36',
    description: 'Honestly kind of genius.',
    likes: '13.7k',
    comments: '1.8k',
    sends: '1.5k',
    isVerified: true,
  },
  {
    id: 37,
    src: '/videos/video37.mp4',
    user: 'TryItGroup',
    avatar: 'avatar37',
    description: 'You won’t regret trying it.',
    likes: '2.8k',
    comments: '190',
    sends: '130',
    isVerified: true,
  },
  {
    id: 38,
    src: '/videos/video38.mp4',
    user: 'OnlyOneCo',
    avatar: 'avatar38',
    description: 'It’s the only one I use now.',
    likes: '11.1k',
    comments: '1.3k',
    sends: '1.1k',
    isVerified: true,
  },
  {
    id: 39,
    src: '/videos/video39.mp4',
    user: 'Hykly',
    avatar: 'avatar39',
    description: 'I get the hype now.',
    likes: '19.4k',
    comments: '2.5k',
    sends: '2.0k',
    isVerified: true,
  },
  {
    id: 40,
    src: '/videos/video40.mp4',
    user: 'UnexpectedLabs',
    avatar: 'avatar40',
    description: 'Didn’t expect it to be this good. #wow',
    likes: '7.5k',
    comments: '600',
    sends: '520'
  },
  {
    id: 41,
    src: '/videos/video41.mp4',
    user: 'Shiftio',
    avatar: 'avatar41',
    description: 'A tiny change with a big payoff.',
    likes: '4.8k',
    comments: '320',
    sends: '280',
    isVerified: true,
  },
  {
    id: 42,
    src: '/videos/video42.mp4',
    user: 'FastEffectCo',
    avatar: 'avatar42',
    description: 'I can’t believe it worked this fast.',
    likes: '16.9k',
    comments: '2.2k',
    sends: '1.9k',
    isVerified: true,
  },
  {
    id: 43,
    src: '/videos/video43.mp4',
    user: 'Clikra',
    avatar: 'avatar43',
    description: 'This is where it clicked for me. #makesense',
    likes: '5.5k',
    comments: '480',
    sends: '410',
    isVerified: true,
  },
  {
    id: 44,
    src: '/videos/video44.mp4',
    user: 'SoonerCoOfficial',
    avatar: 'avatar44',
    description: 'Why didn’t I buy this sooner?',
    likes: '10.1k',
    comments: '1.0k',
    sends: '900',
    isVerified: true,
  },
  {
    id: 45,
    src: '/videos/video45.mp4',
    user: 'SenseMakersBrand',
    avatar: 'avatar45',
    description: 'It just makes sense. #simple',
    likes: '3.6k',
    comments: '280',
    sends: '210'
  },
  {
    id: 46,
    src: '/videos/video46.mp4',
    user: 'WalletHappyCo',
    avatar: 'avatar46',
    description: 'My wallet cried but I’m happy.',
    likes: '8.3k',
    comments: '750',
    sends: '600',
    isVerified: true,
  },
  {
    id: 47,
    src: '/videos/video47.mp4',
    user: 'SellPointLabs',
    avatar: 'avatar47',
    description: 'This is the part that sold me.',
    likes: '6.9k',
    comments: '550',
    sends: '480',
    isVerified: true,
  },
  {
    id: 48,
    src: '/videos/video48.mp4',
    user: 'EffortlessCo',
    avatar: 'avatar48',
    description: 'Low effort, high payoff. #effortless',
    likes: '12.0k',
    comments: '1.4k',
    sends: '1.1k',
    isVerified: true,
  },
  {
    id: 49,
    src: '/videos/video49.mp4',
    user: 'Reacto',
    avatar: 'avatar49',
    description: 'Kinda wish I recorded my reaction.',
    likes: '4.2k',
    comments: '310',
    sends: '250',
    isVerified: true,
  },
  {
    id: 50,
    src: '/videos/video50.mp4',
    user: 'Tryst',
    avatar: 'avatar50',
    description: 'You’ll get it once you try. #trustme',
    likes: '2.1k',
    comments: '160',
    sends: '110'
  },
];

    